### ISSUE TITLE
HTML&CSS Kata: Coulette

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#33]
Create the HTML and CSS for the Coulette app.

To give you an impression of the features here is a [minimal unstyled todo app](https://coulette.netlify.app/).

This kata is a preparation for the Coulette Lecture Example which will mainly focus on functionality. This is the chance to prepare the HTML and CSS in advance.

**Comment by glissario** [comment]
Initial implementation:
https://glisscoulette.netlify.app/
