### ISSUE TITLE
Advanced HTML&CSS: Transitions

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#38]
- [ ] Add a transition for the `background-color` for the nav links
  - If your nav links don't have a background color use one or use the transition with another property (i.e. `color`)
- [ ] Add a pseudo class for the `focus` state of the nav links (which then also can use the transition)

**Hints**

```css
.nav-link:focus {
  ...
}
```

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-cv/blob/transitions/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-cv/compare/custom-properties...transitions)

**Comment by glissario** [comment]
done
