### ISSUE TITLE
Intro to Programming with P5: Microsoft Logo

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#51]
- [x] Please create a new sketch
- [x] Change the background of the canvas to white
- [x] Recreate the microsoft logo
  - [ ] The logo is basically four colorful squares with a gutter

**Hints**

The Microsoft logo looks like this.

![image](https://user-images.githubusercontent.com/16404104/123400500-1e9fab00-d5a6-11eb-940b-3b4b10c6afc5.png)

You can use the following CSS color names: tomato, yellowgreen, skyblue, orange

You need to disable outlines for the Microsoft logo.

```js
  function setup() {
    noStroke();
  }
```

**Example Solution**

- [Example solution](https://editor.p5js.org/CodingBootcampsEu/sketches/kn648AesQ)

**Comment by glissario** [comment]
done
