### ISSUE TITLE
P5 Kata: Mouse Coordinates

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#58]
- Create a sketch that displays the current mouse coordinates like [this](https://editor.p5js.org/hypergardens/full/JA2ipFoMp)
  - The mouse coordinates are only displayed when the mouse is pressed
- A minimal example solution can be found [here](https://editor.p5js.org/hypergardens/sketches/JA2ipFoMp)

![mouse-coords](https://user-images.githubusercontent.com/16404104/123773608-12309080-d8cd-11eb-9e04-dd516dbd2b30.gif)

**Hints**

You will need the `text()` function for this kata - so here is the [text() reference](https://p5js.org/reference/#/p5/text)

**Comment by glissario** [comment]
done
