### ISSUE TITLE
First JavaScript Web App: Random Color

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#69]
- [x] Change the text of the header button to "Generate Color"
- [x] Add a paragraph that should display a generated color value
- [x] Change the implementation of the button handler
  - [x] Generate a new random color with the provided code
  - [x] Set the generated color value as the background color of the header
  - [x] Set the color as the text of the paragraph
- [x] Initially generate a random color when entering Coulette

Use the following code to generate a random color.

```js
/**
 * Toggle color of header
 * Generate random number between min and max
 */
function randomNumber(min, max) {
  const num = Math.random() * (max - min + 1) + min;
  return Math.floor(num);
}

/**
 * Generate random hex number for color
 */
function randomHexNumber() {
  let hex = randomNumber(0, 255).toString(16);
  if (hex.length === 1) {
    hex = "0" + hex;
  }
  return hex;
}

/**
 * Generate random hex color
 */
function randomHexColor() {
  const red = randomHexNumber();
  const green = randomHexNumber();
  const blue = randomHexNumber();

  return ("#" + red + green + blue).toUpperCase();
}
```

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-coulette/blob/random-color/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-coulette/compare/toggle-background-color...random-color)

**Comment by glissario** [comment]
https://glisscoulette.netlify.app/

**Comment by glissario** [comment]
added functionality of the two other buttons
