### ISSUE TITLE
First JavaScript Web App: Save Color

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#70]
- [x] Add a new button "Save Color"
- [x] Add a main section that will contain the list of colors
- [x] Add an click event listener for the save button and implement a function that
  - [x] creates a new list element that contains the (last generated) hex value as text 
  - [x] The list element should have the background color of the color it represents
    - You can as well use a child element or pseudo element to show the color
  - [x] Append the new list item to the list of colors

**Hints**

```html
<main>
  <ul id="colors"></ul>
</main>
```

- With more than one button the buttons will need its own `id`

- Read color value

```js
const colorValueEl = document.querySelector("#colorValue");
const color = colorValueEl.innerText;
```

- Create list element

```js
const newColor = document.createElement("li");
// TODO: set necessary properties
colorList.appendChild(newColor);
```

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-coulette/blob/save-color/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-coulette/compare/random-color...save-color)

**Comment by glissario** [comment]
https://glisscoulette.netlify.app/

delete-button not working accurately - have to remove the right position in the array
