### ISSUE TITLE
First JavaScript Web App: Persist Colors in Local Storage

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#75]
- [x] Save your color list in the local storage
- [x] When you reload the website the colors should be loaded from the local storage again

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-coulette/blob/persist-colors-in-localstorage/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-coulette/compare/delete-color...persist-colors-in-localstorage)

**Comment by glissario** [comment]
done and uploaded: https://glisscoulette.netlify.app/
