### ISSUE TITLE
Kata: Quote App

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#84]
Create a quote app using HTML, CSS and JavaScript.

- [x] Create a new repository on GitHub
- [ ] Add Bootstrap as a dependency using NPM
- [x] Use bootstrap to style your application
- [x] Use the [Quote Garden API](https://quote-garden.herokuapp.com/api/v3/quotes/random) for random quotes
- [x] Use `.gitignore` to ignore unnecessary files

**Requirements**

- [x] Display a static default quote and quote author upon start of the app
- [x] Add a button which will get a random quote from the API
- [x] Use bootstrap for the following
  - [x] The quote button
  - [x] The quote and quote author 
- [x] Use semantic HTML
- [x] The header should contain a title and a the quote button
  - [x] Place the title on the left side of the header and the button on the right side 

**Bonus**

- [x] Use Netlify to publish your quote app (can be tricky because of NPM 😎)

**Hints**

- You can mix bootstrap and your own styles.
- Installed npm dependencies are located in the `node_modules` folder - you can directly load the files from there into your app.
- The Bootstrap css file is located in the `dist` folder of the bootstrap package.
- Bootstrap is responsive by default
- All relevant information is located in the [Bootstrap Documentation](https://getbootstrap.com/docs/4.1/getting-started/introduction/)

**Screenshots**

![image](https://user-images.githubusercontent.com/16404104/126598919-6949f779-ad2c-49e7-a8f1-0aa2b92d17fa.png)

![image](https://user-images.githubusercontent.com/16404104/126598954-e525b8e3-9dd4-4ef5-a5ac-78cedfab51b8.png)

**Comment by glissario** [comment]
https://glissquotes.netlify.app/

**Comment by glissario** [comment]
wrong connection of bootstrap
